#!/bin/bash
set -e

CONFIG_DIR="./config"
SRC_INTEGRATION="./custom_components/21energy_heater_control"
DEST_INTEGRATION="$CONFIG_DIR/custom_components/21energy_heater_control"


echo "🛑 Stopping any running Home Assistant..."
pkill -f "homeassistant" || true

echo "🔗 Setting up symlink for custom integration..."
mkdir -p "$CONFIG_DIR/custom_components"
ln -sfn "$(realpath "$SRC_INTEGRATION")" "$DEST_INTEGRATION"

echo "🚀 Starting Home Assistant..."
echo "🌐 Home Assistant is starting. Access it at: http://localhost:8123"
source venv/bin/activate
hass -c "$CONFIG_DIR"
